version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: headless_wp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - headless_wp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache  
  redis:
    image: redis:7-alpine
    container_name: headless_wp_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - headless_wp_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_password", "ping"]
      timeout: 10s
      retries: 5

  # WordPress Backend
  wordpress:
    image: wordpress:6.4-php8.2-apache
    container_name: headless_wp_backend
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
      WORDPRESS_DEBUG_DISPLAY: 0
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/themes:/var/www/html/wp-content/themes/custom
      - ./wordpress/plugins:/var/www/html/wp-content/plugins/custom
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - headless_wp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/admin-ajax.php"]
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  headless_wp_network:
    driver: bridge